network/api_test.go

Use standard testing.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Remove check package.

---

authz/api_test.go
network/api_test.go
sdk/sdk_test.go
volume/api_test.go

Signed-off-by: David Calavera <david.calavera@gmail.com>

Fix Fatalf directives.

---

network/api_test.go

Signed-off-by: David Calavera <david.calavera@gmail.com>

Do not use standard ports for testing.

---

authz/api.go
network/README.md
network/api.go
network/api_test.go
volume/api.go

Signed-off-by: Jessica Frazelle <acidburn@docker.com>

fix import paths

---

authz/README.md

Just brings the README.md inline with the others :P

authz: README.md: remove Credits

---

sdk/handler.go
volume/api.go
volume/api_test.go

Also adds tests for the volume API

Add volume List/Get calls

---

README.md
authorization/README.md
authorization/api.go
authorization/api_test.go

Rename authz to authorization

---

ipam/api.go
network/api.go

Methods based on current documentation.

Created IPAM plugin

---

README.md

Signed-off-by: Dave Tucker <dt@docker.com>

Add link to AuthZ Docs

---

.travis.yml
Makefile
network/api.go
network/api_test.go

- Fix network ports (my bad)
- Fix failing test since the `CapabilitiesResponse` was added
- Create Makefile for ease of running tests using Docker
- make test = with docker
- make test-local = using local go
Signed-off-by: Dave Tucker <dt@docker.com>

Fix tests and add Makefile

---

network/api.go

Signed-off-by: Dave Tucker <dt@docker.com>

Updates to network api for 1.10

---

sdk/unix_listener.go

we basically want plugins to be socket activated when possible, I can write some docs for docker/docker to explain more about this. So when/if a plugin dies the socket doesn't and can re-run the plugin again.

sdk: support systemd socket activation

---

volume/README.md

Fixed a little typo
Signed-off-by: Robin Naundorf <r.naundorf@fh-muenster.de>

Fixed Typo in Volume README

---

volume/api.go
volume/api_test.go
volume/shim/shim.go
volume/shim/shim_test.go

Signed-off-by: Brian Goff <cpuguy83@gmail.com>

Add support for volume capabilities endpoint

---

volume/api.go
volume/api_test.go
volume/shim/shim.go

Renamed MountID to ID, verified with docker 1,.12 and am able to get the mount ID in my plugin on a mount request.

Rename MountID to ID in Request struct

---

volume/api.go
volume/shim/shim.go

Added support for returning status for a volume from the plugin.

Add volume status for Get().

---

authorization/api_test.go

Signed-off-by: Lorenzo Fontana <fontanalorenzo@me.com>

Test authz helper

---

authorization/api_test.go
network/api_test.go
sdk/handler.go
sdk/tcp_listener.go

sdk: ServeTCP with tls.Config

---

authorization/README.md

Signed-off-by: Chaitanya Prakash N cpdevws@gmail.com

Fixing the example to use the correct API as per latest changes

---

graphdriver/api.go
graphdriver/api_test.go
graphdriver/shim/shim.go
graphdriver/shim/shim_test.go
volume/api_test.go

Add support for the GraphDriver.Capabilities call added in https://github.com/moby/moby/pull/32092 .

Add support for graphdriver Capabilities call

---

secrets/api.go

Fixes #94
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

Fixing compile error in secrets plugin helper

---

Makefile
authorization/api_test.go
graphdriver/api.go
graphdriver/api_test.go
graphdriver/shim/shim.go
graphdriver/shim/shim_test.go
network/api_test.go
volume/api.go

Race condition in tests causes all the current issues with tests failing.

Race condition in tests

---

secrets/api.go

This is a work in progress and should _not_ be merged until https://github.com/docker/swarmkit/pull/2735 is.

Support DoNotReuse in secrets response

---

.github/workflows/ci.yaml
.travis.yml
Makefile

Travis CI (.org) is no more, so adding a rudimentary action

CI: use GitHub Actions
