network/api.go
network/api_test.go

Exposes GetCapabilities API so that plugins can choose whether to be global or local scope. Adds a check so that existing plugins that do not implement this function continue to work with local scope.

Allow creating network plugins with global scope

---

circle.yml
network/api.go
network/api_test.go

Well known ports require root access.
Change to use ephemeral ports.
Signed-off-by: Dave Tucker <dt@docker.com>

Fix networking tests

---

volume/shim.go
volume/shim_test.go

This allows a plugin writer to not care about the plugin API and rather
focus on the volume driver API from engine.
As an example, engine's built-in `local` driver can operate as a plugin
with no extra effort with this shim layer.

Adds shim layer for writing volume drivers

---

sdk/unix_listener.go

sdk: check systemd running for socket activation

---

volume/shim/shim.go
volume/shim/shim_test.go

This makes it so users of github.com/docker/go-plugin-helpers/volume do
not need to import github.com/docker/docker/volume since it's only
needed for the shim to satisfy docker interfaces.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>

Move volume shim to own package

---

README.md
graphdriver/README.md
graphdriver/api.go
graphdriver/api_test.go
graphdriver/shim/shim.go
graphdriver/shim/shim_test.go
sdk/encoder.go

Thanks to @dave-tucker for the original version of this patch (see. #33). I've changed the interface slightly to simplify the creation of new plugins and I've added some tests, inspired from the volume helpers.
I have an other patch to add `shim.go` so we can use built-in graphdrivers as plugins, I need to write some test first (and figure how I can test that properly).

Add graphdriver helpers

---

Makefile
authorization/api.go

We can't use structs with big integers in authorization Request otherwise :smile_cat: 
@vdemeester PTAL

authorization: decode using numbers

---

network/api.go

https://github.com/docker/docker/pull/27287 brought in the support for swarm-mode network v1 plugins. These 2 APIs are introduced to support remote plugins in swarm-mode.
Also fixed a minor error handling issue in createEndpointPath where the EncodeResponse is called twice incorrectly
Signed-off-by: Madhu Venugopal madhu@docker.com

add AllocateNetwork and FreeNetwork plugin apis

---

sdk/handler.go
sdk/unix_listener.go
sdk/unix_listener_unsupported.go

This makes it possible to cross-compile plugins.
Builds on top of docker/go-connections#26
If a plugin author wants to do group lookup, they can do it in their own
way and pass in the gid.
As is, this is too much for a library and makes it incredibly annoying
to use.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>

Remove use of cgo

---

authorization/README.md

Modifed docker-novolume-plugin link to moved repository 
[runcom/docker-novolume-plugin](https://github.com/runcom/docker-novolume-plugin) moved to [projectatomic/docker-novolume-plugin](https://github.com/projectatomic/docker-novolume-plugin)

Fix Docker authorization extension full-example link

---

sdk/unix_listener.go
sdk/unix_listener_nosystemd.go
sdk/unix_listener_systemd.go

Signed-off-by: Tibor Vass <teabee89@gmail.com>

Allow building without systemd dependency

---

sdk/encoder.go
sdk/pool.go

`ReadAll` could be reading lots of data, e.g. an image layer.
We also don't want to just use `io.Copy` which will allocate a new
buffer on each call, but instead use a shared buffer pool.
ping @samoht

Don't use ReadAll in sdk.StreamResponse

---

authorization/api_test.go
network/README.md
network/api_test.go
sdk/handler.go
sdk/spec_file_generator.go
sdk/tcp_listener.go
sdk/unix_listener_unsupported.go
sdk/windows_listener.go
sdk/windows_listener_unsupported.go
sdk/windows_pipe_config.go

This lets us implement remote drivers on Windows that use named pipes for docker daemon - driver communication.
Signed-off-by: Michal Kostrzewa <kostrzewa.michal@o2.pl>

Implement a windows listener using named pipes.

---

volume/README.md
volume/api.go
volume/api_test.go
volume/shim/shim.go
volume/shim/shim_test.go

This would fix https://github.com/docker/go-plugins-helpers/issues/41 and makes the usage of the volume API a little bit more clear. The volume API now has the same stile like the network API. (This PR probably breaks all existing Volume Plugins if they don't use a dependency mgmt. tool)
cc @dave-tucker

Refactor Volume

---

Makefile
authorization/api.go
authorization/api_test.go

As for other plugin/driver in this repository, these struct should be
defined in without dependency to a `docker/docker` struct (especially
in `pkg/*` folder).
This move the definition of these structs in `authorization`, instead
of type aliasing, and thus removes dependency on `pkg/authorization`
from this package.
cc @dnephin @thaJeztah @vieux @cpuguy83 @dave-tucker @runcom 
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Import Request/Response struct from docker/docker/pkg/authorization

---

network/api.go
network/api_test.go

due to the libnetwork remote api change in https://github.com/docker/libnetwork/commit/596122e05edd3e9712256ea309746ff903409446
Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>

support ConnectivityScope in network plugin

---

authorization/api.go
graphdriver/api.go
graphdriver/api_test.go
graphdriver/shim/shim_test.go
ipam/api.go
network/api.go
sdk/encoder.go
volume/api.go
volume/api_test.go
volume/shim/shim.go

sorry it's a big PR, reading commit by commit could be helpful.
I started refactoring one side and then `¯\_(ツ)_/¯` started from https://github.com/docker/go-plugins-helpers/pull/76
The bunch of the refactor started from here.
some API (graphdriver) had a `Err` field in almost every Responses, and sometimes duplicated (empty) responses
some API (volume) had a `Err` field in *some* Responses and sometimes used `ErrorResponse`.
some API (network, ipam) had no `Err` and used a dedicated `ErrorResponse` for error.
Basically graphdriver and network/ipam were totally different and volume was in the middle.
I decided to uniform everything like network and ipam.
It also adds a bunch of fixes, such as adding missing multiple `return`
ping @cpuguy83 for some reason I cannot add you a reviewer.

multiple refactors and fixes

---

secrets/README.md
secrets/api.go
secrets/api_test.go

This commit introduces a pluggable secrets backend as implemented in:
1. docker/swarmkit@eebac27434d34708fac993f9f5181d106c5c2fae
2. docker/docker@08f7cf05268782a0dd8e4c41a4cc65fdf78d09f2
3. [Design](https://docs.google.com/document/d/1kNA6apIFAiaE9d96A2_rcEulVrglvq05zEXGdijSZac)
Signed-off-by: Liron Levin <liron@twistlock.com>

plugable secret backend

---

volume/api.go

The CreatedAt property is missing from the Volume struct, this means docker volume inspect returns 
```
[
{
"CreatedAt": "0001-01-01T00:00:00Z",
"Driver": "volume-driver-test:latest",
"Labels": {},
"Mountpoint": "/mnt/data/volumes/test",
"Name": "test",
"Options": {},
"Scope": "global"
}
]
```
Adding this and returning it fixes the problem.

Added CreatedAt property to Volume struct

---

secrets/api.go
secrets/api_test.go

This provides more context for the secret driver when it is requested
the value for the secret. It is useful both for audit purposes, e.g. an
external system logging which task requested what secret, as well as
in a scenario where the plugin would return a different value (or
error) based on e.g. labels on the secret.
Blocks https://github.com/docker/swarmkit/pull/2738.
Signed-off-by: Sune Keller <absukl@almbrand.dk>

Add additional info for secret drivers

---

volume/README.md

Docker Volume plugin emulating the HPE Nimble Storage plugin on top of OpenZFS.

Inclusion of Nemo in the examples

---

Makefile
authorization/api_test.go
volume/api.go

Empty CreatedAt values causes errors in docker

Ignore empty CreatedAt

---

graphdriver/api.go

Fix documentation link in API go file commentary due to files moved in moby/moby@677fa03654886ee776ff478c30681d5376cfc196 in 2016 and once more in moby/moby@b5579a4ce33af4c1f67118e11b5a01008a36d26a in 2017.

Fix documentation link

---

Makefile

Go version updated from 1.11 to 1.13, golint import path changed to actual one.

Bump go version and update golint import path

---

network/api.go
volume/api.go

This change allows to prevent spamming system logs.
The current behavior is preserved, by default API requests get logged to standard output. This is useful if plugin is distributed as image for `docker plugin install`.
However, plugins running as a systemd service might produce too much output especially under high request load. In such cases plugin authors can leverage two new boolean flags: `volume.Trace` or `network.Trace`.
Setting these to `false` will supress trace logging.
I deliberately chose such simple interface as externally visible booleans. Plugin authors are free to use any logic around this: logging levels, config files, environment settings and so on.
**EDIT 1:** Based on review comments the logging has been completely removed.
Fixes #126
Signed-off-by: Ivan Andreev …

Put trace logging under control

---

MAINTAINERS

- closes https://github.com/docker/go-plugins-helpers/issues/132
This repository went not looked after for some time, and the
runtime team will be looking at refreshing it a bit.

refresh maintainers list
